version: '3.0'
services:
  web:
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "8080:8080"
    command: yarn start
    volumes:
      - node_modules:/app/node_modules
  nginx:
    image: nginx:alpine
    ports:
      - "10080:80"
    depends_on:
      - web
    volumes:
      - ./config/nginx:/etc/nginx:ro
      - ./public:/usr/share/nginx/html:ro
volumes:
  node_modules:
